#####################
##### Automação #####
#####################

################## Aquario ################

 - alias: aquario_luz_ligar
   trigger:
     - platform: time
       after: '9:00:00'
   action:
     - service: light.turn_on
       entity_id: light.luz_aquario

 - alias: aquario_luz_desligar
   trigger:
     - platform: time
       after: '21:00:00'
   action:
     - service: light.turn_off
       entity_id: light.luz_aquario

 - alias: aquario_racao_acionar
   trigger:
     - platform: time
       after: '20:05:00'
   action:
     service: homeassistant.turn_on 
     entity_id: script.aquario_racao_timer

#
# - alias: notificar
#   trigger:
#     platform: mqtt
#     topic: "casa/aquario/racao"
#     payload: 'ON'
#   action:
#     service: notify.telegram_teste
#     data:
#       message: 'Ração do aquario acionada.'

############# Luz da Frente ############
 - alias: luz_frente_on
   trigger:
     platform: sun
     event: sunset
   action:
     service: light.turn_on
     entity_id: light.luz_frente

 - alias: luz_frente_off
   trigger:
     platform: time
     after: '21:30:00'
   action:
     service: light.turn_off
     entity_id: light.luz_frente

########### Notificar início do HASS #####
 - alias: notificar_start
   trigger:
     platform: event
     event_type: homeassistant_start
   action:
     service: notify.telegram_teste
     data:
       message: 'Hass inicializado.'

################ Alarme ####################
 - alias: alarme_evento
   trigger:
     - platform: mqtt
       topic: "mygateway1-out/2/5/1/0/33" 
       payload: '182113829'
     #Sensor porta sala
     - platform: mqtt
       topic: "mygateway1-out/2/5/1/0/33" 
       payload: '193271205'
   condition:
     - condition: state
       entity_id: alarm_control_panel.ha_alarm
       state: 'armed_away'
   action:
     service: alarm_control_panel.alarm_trigger
     entity_id: alarm_control_panel.ha_alarm

 - alias: alarm_dispaarar
   trigger:
     platform: state
     entity_id: alarm_control_panel.ha_alarm
     state: 'triggered'
   action:
     service: homeassistant.turn_on
     entity_id: light.luz2
 
 - alias: alarm_desligar
   trigger:
     platform: state
     entity_id: alarm_control_panel.ha_alarm
     state: 'disarmed'
   action:
     - service: homeassistant.turn_off
       entity_id: light.luz2
     - service: notify.telegram_teste
       data:
         message: 'Alarme da casa disparado.'