########################
##### Configuração #####
########################

homeassistant:
  name: Casa
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: America/Cuiaba
  temperature_unit: C
  customize: !include_dir_merge_named customize

frontend:
http:
updater:
conversation:
history:
logbook:
sun:
  
################ Includes #######################
group: !include_dir_merge_named group
switch: !include switches.yaml
light: !include light.yaml
automation: !include_dir_merge_list automation
script: !include_dir_merge_named script
shell_command: !include shell_commands.yaml
sensor: !include sensor.yaml

notify:
  - platform: telegram
    name: telegram_teste
    api_key: !secret telegram_api_key
    chat_id: !secret telegram_chat_id

mqtt:
  broker: localhost
  port: 1883
  client_id: home-assistant-1

alarm_control_panel:
  platform: manual
  pending_time: 5