########################
##### Configuração #####
########################

homeassistant:
  name: Casa
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevations
  unit_system: metric
  time_zone: America/Cuiaba
  temperature_unit: C
  customize: !include_dir_merge_named customize
  packages: !include_dir_named package
   
frontend:
http:
  api_password: !secret api_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.168.1.0/24
  ip_ban_enabled: True
  login_attempts_threshold: 3

updater:
history:
recorder:
logbook:
conversation:
sun:
ios:
  
################ Includes #######################
group: !include_dir_merge_named group
script: !include_dir_merge_named script

switch: !include switches.yaml
light: !include light.yaml
automation: !include_dir_merge_list automation
scene: !include scene.yaml
#shell_command: !include shell_commands.yaml
sensor: !include_dir_merge_list sensor
#binary_sensor: !include_dir_merge_list binay_sensor
binary_sensor: !include binary_sensor.yaml
input_select: !include input_select.yaml

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret chat_id_jonathas

notify:
  - platform: telegram
    name: telegram_jonathas
    chat_id: !secret chat_id_jonathas

mqtt:
  broker: localhost
  port: 1883
  client_id: homeassistant

alarm_control_panel:
  platform: manual
  pending_time: 5

#device_tracker:
#  - platform: nmap_tracker
#    hosts: 192.168.1.1/24 
#    interval_seconds: 30

google_assistant:
  project_id: !secret project_id
  client_id: !secret client_id
  access_token: !secret access_token
  agent_user_id: !secret agent_user_id
#  api_key: !secret api_key
  exposed_domains:
    - switch
    - light
    - sensor
    - group