########################
##### Configuração #####
########################

homeassistant:
  name: Casa
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: America/Cuiaba
  temperature_unit: C
  customize: !include_dir_merge_named customize

frontend:
http:
updater:
conversation:
history:
logbook:
sun:
  
################ Includes #######################
group: !include_dir_merge_named group
script: !include_dir_merge_named script

switch: !include switches.yaml
light: !include light.yaml
automation: !include_dir_merge_list automation
shell_command: !include shell_commands.yaml
sensor: !include_dir_merge_list sensor
#binary_sensor: !include_dir_merge_list binay_sensor
binary_sensor: !include binary_sensor.yaml

logger:
  default: warn
  #default: error
  logs:
    homeassistant.components.binary_sensor: debug
#    homeassistant.components.sensor: debug
#    homeassistant.components.camera: debug
#    homeassistant.components.discovery: warn
#    homeassistant.components.http: warn
#    homeassistant.core: debug

notify:
  - platform: telegram
    name: telegram_jonathas
    api_key: !secret telegram_api_key
    chat_id: !secret telegram_chat_id

mqtt:
  broker: localhost
  port: 1883
  client_id: home-assistant-1

alarm_control_panel:
  platform: manual
  pending_time: 5