####################
##### Sensores #####
####################
#
#  - platform: yweather
#  woeid: 26802097
#  forecast: 3
# monitored_conditions:
#   - weather
#   - weather_current
#   - temp_min
#   - temp_max
#   - humidity
#   - temperature

#  - platform: mqtt
#    state_topic: 'mygateway1-out/2/3/1/0/0'
#    name: 'Temperatura'
#    unit_of_measurement: '°C'
#   value_template: '{{ value_json.temperature }}'

#  - platform: mqtt
#    state_topic: 'mygateway1-out/2/4/1/0/1'
#    name: 'Umidade'
#    unit_of_measurement: '%'
#   value_template: '{{ value_json.humidity }}'

- platform: mqtt
  state_topic: "casa/aquario/temperatura"
  name: "Temperatura Aquario"
  unit_of_measurement: "°C"
  qos: 1

- platform: mqtt
  state_topic: "casa/icm01/temperatura"
  name: "Temperatura Quintal"
  unit_of_measurement: "°C"
  qos: 1

- platform: mqtt
  state_topic: "casa/abajur/ldr"
  name: "Abajur Sensor Luz"
  qos: 1

- platform: command_line
  name: "SSL cert expiry"
  unit_of_measurement: days
  scan_interval: 10800
  command: "ssl-cert-check -b -c /etc/letsencrypt/live/examplehome.duckdns.org/cert.pem | awk '{ print $NF }'"