- alias: Ligar luz do abajur por movimento
  trigger:
    - platform: state
      entity_id: binary_sensor.abajur_sensor_pir
      to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: script.timer_pir_abajur

