- alias: luz_frente_on
  trigger:
    platform: sun
    event: sunset
  action:
    service: light.turn_on
    entity_id: light.luz_frente

- alias: luz_frente_off
  trigger:
    platform: time
    after: '21:30:00'
  action:
    service: light.turn_off
    entity_id: light.luz_frente
