- alias: luz_frente_on
  trigger:
    platform: sun
    event: sunset
    offset: "+00:20:00"
  action:
    service: light.turn_on
    entity_id: light.luz_frente

- alias: luz_frente_off
  trigger:
    platform: time
    at: '21:30:00'
  action:
    service: light.turn_off
    entity_id: light.luz_frente

#- alias: luz_frente_on_rf
#  trigger:
#  - platform: mqtt
#      topic: "casa/gateway_rf/433toMQTT" 
#      payload: '159460757'
#  
#  action:
#    service: homeassistant.turn_on
#    entity_id: light.luz_frente
#
#- alias: luz_frente_on_rf_10_minutos
#  trigger:
#    platform: state
#    entity_id: sensor.motion_sensor
#    to: 'ON'
#    for:
#      minutes: 10
#  action:
#    service: homeassistant.turn_off
#    entity_id: light.luz_frente
