- alias: Ligar luz da sala tv por movimento
  trigger:
    - platform: state
      entity_id: binary_sensor.salatv_sensor_pir
      to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: script.timer_pir_salatv