- alias: notificao_inicializacao
  trigger:
    platform: event
    event_type: homeassistant_start
  action:
    - delay: 00:01:00
    - service: notify.ios_jonathas
      data:
        message: 'Home Assistant inicializado.'

- alias: notificar
  trigger:
    platform: mqtt
    topic: "casa/aquario/racao"
    payload: 'ON'
  action:
    service: notify.ios_jonathas
    data:
        message: "Something happened at home!"
        data:
          push:
            badge: 0