- alias: notificao_inicializacao
  trigger:
    platform: event
    event_type: homeassistant_start
  action:
    - delay: 00:00:30
    - service: notify.telegram_jonathas
      data:
        message: 'Home Assistant inicializado.'

- alias: notificar_ratoeira_armada
  trigger:
    platform: mqtt
    topic: "casa/ratoeira/status"
    payload: 'Armada'
  action:
    service: notify.telegram_jonathas
    data:
        message: "Ratoeira armada!"

- alias: notificar_ratoeira_disparada
  trigger:
    platform: mqtt
    topic: "casa/ratoeira/status"
    payload: 'Disparada'
  action:
    service: notify.telegram_jonathas
    data:
        message: "Ratoeira disparada!"
