light:
  - platform: mqtt
    name: gateway_rf_rele1
    state_topic: "casa/gateway_rf/rele1"
    command_topic: "casa/gateway_rf/rele1/set"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
    optimistic: false
    
  - platform: mqtt
    name: gateway_rf_rele2
    state_topic: "casa/gateway_rf/rele2"
    command_topic: "casa/gateway_rf/rele2/set"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
    optimistic: false
  - platform: mqtt
    name: gateway_rf_rele3
    state_topic: "casa/gateway_rf/rele3"
    command_topic: "casa/gateway_rf/rele3/set"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
    optimistic: false

sensor:
  - platform: mqtt
    name: "gateway_rf433"
    state_topic: "casa/gateway_rf/433toMQTT"
    expire_after: 5


group:
  gateway_rf:
    name: "Gataway RF"
    entities:
      - light.gateway_rf_rele1
      - light.gateway_rf_rele2
      - light.gateway_rf_rele3
      - sensor.gateway_rf433
