
light:
  - platform: mqtt
    name: icm02_rele1
    state_topic: "casa/icm02/rele1"
    command_topic: "casa/icm02/rele1/set"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
    optimistic: false
    
  - platform: mqtt
    name: icm02_rele2
    state_topic: "casa/icm02/rele2"
    command_topic: "casa/icm02/rele2/set"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
    optimistic: false

group:
  icm02:
    name: "ICM02"
    entities:
      - light.icm02_rele1
      - light.icm02_rele2

timer:
  icm02_rele2:
    duration: '00:15:00'

automation:
## Luz acionada por movimento por 15 minutos
  - id: icm02_rele2_timer_off
    alias: "Luz armario timer off"
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.icm02_rele2
    action:
      service: homeassistant.turn_off
      entity_id: light.icm02_rele2

  - id: icm02_rele2_timer_on
    alias: "Luz armario timer on"
    trigger:
      - platform: state
        entity_id: sensor.gateway_rf433
        to: !secret rf433_sensor_pir_cozinha
    condition:
      - condition: time
        after: '22:00:00'
        before: '06:00:00'
    action:
      - service: homeassistant.turn_on
        entity_id: light.icm02_rele2
      - service: timer.start
        entity_id: timer.icm02_rele2
